RENAMES = {
    'breakwtr_cl': 'breakwater_cl',
    'cattlstp_pnt': 'cattlestop_pnt',
    'cblwy_ind_cl': 'cableway_industrial_cl',
    'cblwy_peo_cl': 'cableway_people_cl',
    'descrip_text': 'descriptive_text',
    'dredg_tl_cl': 'dredge_tailing_cl',
    'embankmnt_cl': 'embankment_cl',
    'ferry_cr_cl': 'ferry_crossing_cl',
    'fish_fm_poly': 'fish_farm_poly',
    'floodgte_pnt': 'floodgate_pnt',
    'gas_val_pnt': 'gas_valve_pnt',
    'geo_name': 'geographic_name',
    'gl_lake_poly': 'glacial_lake_poly',
    'golf_crs_pnt': 'golf_course_pnt',
    'golf_crs_poly': 'golf_course_poly',
    'grav_pit_poly': 'gravel_pit_poly',
    'hist_ste_pnt': 'historic_site_pnt',
    'ice_clf_edge': 'ice_cliff_edge',
    'ice_strm_cl': 'ice_stream_pnt',
    'marne_fm_cl': 'marine_farm_cl',
    'marne_fm_poly': 'marine_farm_poly',
    'melt_strm_cl': 'melt_stream_cl',
    'moran_wl_poly': 'moraine_wall_poly',
    'pumce_pt_poly': 'pumice_pit_poly',
    'racetrk_cl': 'racetrack_cl',
    'racetrk_pnt': 'racetrack_pnt',
    'racetrk_poly': 'racetrack_poly',
    'radar_dm_pnt': 'radar_dome_pnt',
    'rail_stn_pnt': 'rail_station_pnt',
    'reservr_poly': 'reservoir_poly',
    'res_area_poly': 'residential_area_poly',
    'rifle_rg_poly': 'rifle_range_poly',
    'rock_out_pnt': 'rock_outcrop_pnt',
    'sat_stn_pnt': 'satellite_station_pnt',
    'scatscrb_poly': 'scattered_scrub_poly',
    'shelt_blt_cl': 'shelter_belt_cl',
    'showgrd_poly': 'showground_poly',
    'spillwy_edge': 'spillway_edge',
    'sprtfld_poly': 'sportsfield_poly',
    'telephn_cl': 'telephone_cl',
    'waterfal_edg': 'waterfall_edge',
    'waterfal_cl': 'waterfall_cl',
    'waterfal_pnt': 'waterfall_pnt',
    'waterfal_poly': 'waterfall_poly',
    'water_r_cl': 'water_race_cl',
}

for old_name, new_name in RENAMES.iteritems():
    print "UPDATE data_dict_tag SET layer_id = '%s' WHERE layer_id = '%s';" % (new_name, old_name)
